'use client'

import { motion } from 'framer-motion'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger
} from '@/components/ui/accordion'

const faqs = [
  {
    question: 'What is image vectorization?',
    answer: 'Image vectorization is the process of converting raster images (made of pixels) into vector graphics (made of mathematical paths). This allows the image to be scaled to any size without losing quality, making it perfect for logos, icons, and print materials.'
  },
  {
    question: 'What file formats can I convert?',
    answer: 'VectorPro AI supports all common image formats including PNG, JPG/JPEG, WEBP, BMP, and GIF. Simply upload your image and we\'ll convert it to high-quality SVG format.'
  },
  {
    question: 'Is VectorPro AI really free?',
    answer: 'Yes! VectorPro AI is completely free to use with no hidden fees, no signup required, and no watermarks on your downloads. We believe professional-quality vectorization should be accessible to everyone.'
  },
  {
    question: 'How does the quality compare to paid tools?',
    answer: 'VectorPro AI uses advanced hybrid algorithms that rival industry standards like Vector Magic. Our intelligent edge detection, path optimization, and color quantization produce results that are often indistinguishable from expensive paid tools.'
  },
  {
    question: 'Are my images secure?',
    answer: 'Absolutely. Your images are processed securely in memory and are never stored on our servers. After conversion, your files are immediately deleted. We prioritize your privacy and data security.'
  },
  {
    question: 'What can I do with the SVG files?',
    answer: 'SVG files created by VectorPro AI are fully editable in any vector graphics software including Adobe Illustrator, Inkscape, Figma, and Canva. You can also edit them directly in code editors since SVG is XML-based.'
  },
  {
    question: 'What\'s the maximum file size?',
    answer: 'You can upload images up to 10MB in size. For best results, we recommend using images with good contrast and clear edges. Larger files may take longer to process.'
  },
  {
    question: 'Can I use this for commercial projects?',
    answer: 'Yes! The SVG files you create are yours to use however you like, including for commercial projects. There are no licensing restrictions on files generated by VectorPro AI.'
  }
]

export function FAQSection() {
  return (
    <>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5 }}
        className="mx-auto max-w-3xl text-center"
      >
        <h2 className="mb-4 text-3xl font-bold tracking-tight sm:text-4xl">
          Frequently Asked Questions
        </h2>
        <p className="mb-12 text-lg text-slate-600 dark:text-slate-400">
          Everything you need to know about VectorPro AI
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="mx-auto max-w-3xl"
      >
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="rounded-lg border bg-white px-6 dark:bg-slate-950"
              >
                <AccordionTrigger className="text-left font-semibold text-slate-900 hover:no-underline dark:text-slate-100">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-slate-600 dark:text-slate-400">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </motion.div>
    </>
  )
}
